### ISSUE TITLE
Add Facebook social media link to header

### ISSUE THREAD

**Issue by alextilot** [amelioro/ameliorate#124]
**Is your feature request related to a problem? Please describe.**
Allow users who are on the app find a community (Facebook).

**Describe the solution you'd like**
A button in the header with Facebook logo.
TODO: Ask for Facebook Page URL

**Describe alternatives you've considered**
In the future social links may change.

**Additional context**
Social Media Link Examples
![image](https://user-images.githubusercontent.com/34109200/233792525-2c5b6bb2-d398-4e6b-8807-c76734f083d4.png)

**Technical ideas**
Modular design.

**Comment by amelia2802** [comment]
Hi @alextilot ,
I would like to work on this issue. Before I get started, I have a couple of questions regarding the issue.

- Can you provide more details on where the Facebook link should be directed to? 
- Also, are there any specific design guidelines that I should follow for the button?

I'm looking forward to working on this issue and creating a design that meets the needs of the project.

**Comment by keyserj** [comment]
Welcome to the project @amelia2802 🙂

@alextilot @amelia2802 :
1. I've created a Facebook page for the project, URL: https://www.facebook.com/profile.php?id=100091844721178
2. The Facebook page's purpose will be to allow people to get updates on the project. I think a link to the page would fit better in a footer (e.g. see footers at https://reactflow.dev/, https://react.dev/), but we don't have a footer yet and I'm not 100% sure it's worth taking up the app's workspace area with one. That being said, I think putting the link in the header is fine for now, to the left of the GitHub link
3. As for design, try to get an icon that matches the style of the GitHub icon - circular, with a black version and white version based on the theme's light/dark mode. There should be official icons that Facebook makes available for things like this
4. Out of curiosity, how did you find out about this project?

**Comment by amelia2802** [comment]
Great to hear that! I'm excited to contribute on this project and I found out about this issue through [Good First Issue](https://goodfirstissues.com/) :)
