### ISSUE TITLE
Add Feedback option via email.

### ISSUE THREAD

**Issue by alextilot** [amelioro/ameliorate#125]
**Is your feature request related to a problem? Please describe.**
As a user I  want to be able to send feedback via email so that I can stay anonymous.

**Describe the solution you'd like**
There are two options:
1) Use a link that opens the user's own email with auto filled options.
2) Implement a form on the website that takes these parameters:
    - user email: optional
    - subject/ title: required
    - body text: required

**Describe alternatives you've considered**
Survey format.
Open to ideas.

**Additional context**

**Technical ideas**
Endpoint for feedback:  "ameliorate.app@gmail.com"

Opening the users email automatically: [Automatically open default email client and pre-populate content](https://stackoverflow.com/questions/13231125/automatically-open-default-email-client-and-pre-populate-content)

Blog post on email sends and nodejs [Sending emails with Node.js](https://mailtrap.io/blog/send-emails-with-nodejs/)

**Comment by keyserj** [comment]
Eh honestly I'm not sure if this will ever be worth doing, since we have a feedback button that links to a page with an email specified, and I think people should be able to figure it out from there. Let me know if you think otherwise
