### ISSUE TITLE
Add demo images to home page in carousel

### ISSUE THREAD

**Issue by keyserj** [amelioro/ameliorate#146]
**Is your feature request related to a problem? Please describe.**
We've got a nice demo video on the home page to showcase the tool, but we should throw some pictures in there too, so that people can get the idea even if they don't want to watch a video

**Describe the solution you'd like**
Using a carousel seems good. Don't auto switch slides. Might need to play with whatever carousel options there are to see what looks nice
![image](https://github.com/amelioro/ameliorate/assets/13872370/10f968a0-603a-4b45-9bef-00908a7842fa)

As for which images to use - I think the three at the [top of the readme](https://github.com/amelioro/ameliorate#ameliorate) would be good

**Describe alternatives you've considered**

**Additional context**

**Technical ideas**
[react-material-ui-carousel](https://github.com/Learus/react-material-ui-carousel) looks like a good carousel component

**Comment by kaiseradr** [comment]
I'll take this one :)

**Comment by keyserj** [comment]
Ayyy welcome to the project 🙂 I just updated the contributing guide earlier today because I realized that people can't assign themselves ⚰️let me know if you have any questions

**Comment by kaiseradr** [comment]
Do I need to be given permissions to push a new branch to the repo?

![Image](https://github.com/amelioro/ameliorate/assets/62675315/fc111ee4-a653-48e4-ad02-ca8b3220b635)

**Comment by keyserj** [comment]
Yeah, check out https://opensource.guide/how-to-contribute/#opening-a-pull-request - you'll need to fork the repo and make your changes on the fork. When you put up a PR, you'll merge from your forked repo

**Comment by kaiseradr** [comment]
I have another workflow question. I have forked your project, created a new branch for the feature I'm working on, and then I submitted a PR. I made it a rough draft with the intention to make follow-up commits, but I'm wondering if I'll run into permission issues again if I try to make new commits on this PR. If that's true, do I just add commits to my branch on my forked repo and they will be added into PR?

**Comment by kaiseradr** [comment]
Nevermind, disregard. I should have asked ChatGPT first. It gave a great answer. :)

**Comment by keyserj** [comment]
In case ChatGPT didn't say - the changes in a PR are just a comparison between two branches, showing the changes in the "from" branch that aren't on the other branch. In this case, your PR is comparing the upstream repo's main branch with the forked repo's `add-demo-images-...` branch.
![image](https://github.com/amelioro/ameliorate/assets/13872370/a1873288-d9f0-458b-bbc1-2e40d085e9d2)

This is why you can continue making changes to your branch as you were doing, and they will show up on the PR. Permission issues should only exist if you try to change branches on this upstream repo.

**Comment by kaiseradr** [comment]
Cool, thanks for the clarification. Yeah, seeing the comparison of the branches on the PR makes it clear.
