### ISSUE TITLE
Add tooltip for "view criteria table" and "view claims" buttons

### ISSUE THREAD

**Issue by keyserj** [amelioro/ameliorate#147]
**Is your feature request related to a problem? Please describe.**
The toolbar buttons and add node buttons already have tooltips, but the node indicator buttons do not yet. We should add these.
![image](https://github.com/amelioro/ameliorate/assets/13872370/a19592c8-4253-4bfe-a6b1-431dd383c7f9)

**Describe the solution you'd like**
Something like this (Material UI Tooltip)
![image](https://github.com/amelioro/ameliorate/assets/13872370/3561d781-1706-4e37-8e8e-552afbdda51c)

or like this (html `title` and `aria-label`)
![image](https://github.com/amelioro/ameliorate/assets/13872370/f67722f7-88ec-488a-93d0-01a169a088f2)

We should probably be consistent with these but I'm not actually sure which one is better. Maybe Material UI Tooltip because it must meet Material UI standards?

**Describe alternatives you've considered**

**Additional context**

**Technical ideas**

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue

**Comment by tarunsamanta2k20** [comment]
@keyserj i'd like to work on it

**Comment by keyserj** [comment]
hey @tarunsamanta2k20 welcome to the project 🙂 let me know if you have any questions
