### ISSUE TITLE
Share topic from specific view

### ISSUE THREAD

**Issue by keyserj** [amelioro/ameliorate#214]
**Is your feature request related to a problem? Please describe.**
If I want to share a specific detail of a topic with someone else, right now I have to tell them something like "click on the [problem]'s criteria table". I should be able to share a link that allows someone else to view specifically what I want to share with them.

**Describe the solution you'd like**
Add params to URL to show specific views. Ideas:
- `?table={graphPartId}` (cut the guid off to first 8 chars: 10000 guids has 1% probability collision)
- `?selected={graphPartId}` (cut off to first 8 chars)
- `?claim={graphPartId}`

We should also update the URL with these params when you are viewing them, e.g. select a node, go to a criteria table. This will help users be aware of the functionality.

Questions:
- Would this implementation mean that the browser's navigate back/forward could be relied on rather than using our own (with zustand's undo/redo implementation)?
- Should we make the Topic Views buttons use these params as links? Then they'd be middle-clickable?

**Describe alternatives you've considered**
Could also do format like `?view=table:{graphPartId}`

**Additional context**

**Technical ideas**
- `?selected` should probably use [moveViewportToIncludeNode](https://github.com/amelioro/ameliorate/blob/14cd5ab80c2ae99c612632c76c46e9f484a040d0/src/web/topic/hooks/flowHooks.ts#L63-L70) so that the viewport is updated to have the selected node in view
- Should be able to use nextjs's [router.query.[param]](https://nextjs.org/docs/pages/api-reference/functions/use-router#router-object) to access URL params in a page, similar to [how we access dynamic route slugs](https://github.com/amelioro/ameliorate/blob/234ddaad5ca98ee72ddc6e82edfa14ef0c66617a/src/pages/%5Busername%5D/%5BtopicTitle%5D.page.tsx#L18-L19)
- [Shallow routing](https://nextjs.org/docs/pages/building-your-application/routing/linking-and-navigating#shallow-routing) should be used to update the URL with the params

**Comment by CatGuardian** [comment]
Also include something to bring up the claim table.

**Comment by CatGuardian** [comment]
https://www.npmjs.com/package/qs

**Comment by keyserj** [comment]
Note: careful of how selection works with two diagrams - I think the topic diagram and claim tree can both have separate selections at the same time. We wouldn't want the URL to have the `selected` param for the not-active diagram

**Comment by keyserj** [comment]
Would this implementation mean that the browser's navigate back/forward could be relied on rather than using our own (with zustand's undo/redo implementation)?
