### ISSUE TITLE
Table view for comparing solutions across criteria

### ISSUE THREAD

**Issue by keyserj** [amelioro/ameliorate#33]
**Is your feature request related to a problem? Please describe.**
It's hard to compare solutions without common criteria. We have that, but criteria nodes are annoying to work with because they have too many connections in the problem view.

**Describe the solution you'd like**
A table would be much nicer/conciser, it's built exactly for this kind of thing (where all solution nodes are connected to all criteria). This will essentially be a [decision matrix](https://en.wikipedia.org/wiki/Decision_matrix).

See table in [Figma design](https://www.figma.com/proto/bYNA5pVNoaoWboh6TyBTkb/Understandings---sketches?node-id=325%3A2&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=325%3A2&show-proto-sidebar=1) for how it could work functionally. See [ruminate](https://app.ruminate.io/d/bOUIumwMy-ajEme9dnfLIA) for a decent decision matrix UX.

**Describe alternatives you've considered**

**Additional context**

**Technical ideas**
[Tanstack table](https://github.com/TanStack/table) seems like a popular library for implementing tables that wouldn't have limited features per a pricing model (like MUI tables, which unfortunately require paying at least for row reordering). [Here](https://logrocket-smart-table.netlify.app/) is a decent-looking example table (with implementation described in [this blog post](https://blog.logrocket.com/react-table-complete-guide/)).

**Comment by keyserj** [comment]
Still WIP but some notes for hindsight

Challenges
- Refactor store to “layer” claim diagram > table > problem diagram
  - Currently using one diagram still but using multiple should fix the frequent disorienting when clicking between, and then an overlay solution should be really easy by just making the claim diagram background transparent
- Spent lots of time trying to understand/use table libraries (react-table, MUI table) before realizing they don’t make sense
  - They’re focused on tables based on column headers, not col & row headers
  - Don’t need filtering/sorting functionality
  - Wanted to use own components for cells anyway (to mimic diagram nodes)
  - May eventually use react-table to simplify row/col re-ordering
- Wanted to reuse most of the Node functionality in the table cells (indicators, score, icon)
  - Extracted common component

Questions
- Should all problems show under “Criteria Tables” in side pane, or just those w/rows/cols?
- Increase node size to always 3 lines high?
- Want to be able to conveniently work with ~8 solutions by 8 criteria… should this table be put into a React Flow node to make zooming/panning easy?

**Comment by CatGuardian** [comment]
Questions

* Should all problems show under “Criteria Tables” in side pane, or just those w/rows/cols?
  - Yes. I believe so
  
* Increase node size to always 3 lines high?
  - Depends on if you keep the same component/node in the table header.

* Want to be able to conveniently work with ~8 solutions by 8 criteria… should this table be put into a React Flow node to make zooming/panning easy?
  - Pin a col/header row. And scroll bar
