### ISSUE TITLE
Right clicking when custom context menu is open will open the default menu

### ISSUE THREAD

**Issue by keyserj** [amelioro/ameliorate#38]
**Describe the bug**
When the custom context menu is open, right clicking again should close the menu, but it doesn't - it opens the default menu.

**To Reproduce**
1. Right click on a node
2. Right click again, anywhere
3. Observe that the browser's default context menu is opened

**Expected behavior**
Closes the custom context menu (and does not open the browser's default context menu)

**Screenshots**
![image](https://user-images.githubusercontent.com/13872370/215632803-609a17f5-bfda-4363-bd97-6e8b14eedb45.png)

**Additional context**

**Technical ideas**
- MUI's [example](https://mui.com/material-ui/react-menu/#context-menu) properly closes the custom context menu. Seems like a backdrop is rendered when the context menu is open, and any right-click on the backdrop should trigger closure of the context menu, but for some reason, right-clicking on the backdrop is triggering the default browser's context menu.

**Comment by keyserj** [comment]
I'm leaning towards removing the custom context menu altogether, and putting buttons in the toolbar to replace the menu items.

**Comment by alextilot** [comment]
Disabled browser context menu within diagram.

**Comment by keyserj** [comment]
I think it's fine enough to just disable the context menu. In the future, maybe we could add default context menu options so that right click never does nothing
