### ISSUE TITLE
Filter to this node and its neighbors

### ISSUE THREAD

**Issue by keyserj** [amelioro/ameliorate#380]
### Describe your issue

Sometimes I want to know more about a node and what it's related to, but it's hard to see because the diagram I'm looking at is so cluttered. Some node types have a specific filter to show relevant nodes to the node type, but not all do, and sometimes the specific filter shows more or less than what I care to see.

### Solution you'd like

Button to focus on a specific node, filter out all nodes besides this node and its neighbors.

Probably should add "Nodes to show" to be able to control specific nodes to show:
![image](https://github.com/amelioro/ameliorate/assets/13872370/5f0e6ed3-9a1f-4631-bda2-9910cfbaa988)

"Filter to this node" button can toggle off all info categories and set the nodes to show.

### Questions to answer

- what should the button icon be? maybe like a bullseye
- where should this button go? probably in the upper-right of each node (there should be space after #297 ), but could also live in the Topic Toolbar

### Alternatives you've considered

- double-click to focus on a node

### Additional context

- relevant to #377

**Comment by CatGuardian** [comment]
We should at least make a "Focus to Node" entry in the right click context menu.
