### ISSUE TITLE
Put filter options into URL params

### ISSUE THREAD

**Issue by keyserj** [amelioro/ameliorate#382]
### Describe your issue

It's annoying when I refresh the page and lose my filter. It'd also be nice if I could send a link to someone and they could see exactly what I see - which isn't the case if they don't get my filter.

### Solution you'd like

Encode filter options into URL params

### Questions to answer

- what format to use? would be nice if the params were human readable, but ideally we wouldn't need to manually update the code to include new filter options in the URL params, so a generalized algorithm for encoding is probably best

### Alternatives you've considered

- saving to local storage; this doesn't enable sharing filters with others via URL, or using back to go to previous filter, but could be a short-term solution to save filters beyond refresh

### Additional context

Wait until multiple filters are implemented? Since that might affect how filter options should be encoded in the URL params?

### Technical ideas

- with a generalized encoding algorithm
  - it'd probably be ideal to only add filter options that are relevant for the selected type. e.g. right now, with type = "none", there might still be a `centralProblemId` set, which is nice for remembering params when switching between filters, but is a bit much for putting in the URL
  - still would prefer to shorten uuids

### Technical questions

- how will store schema refactoring be handled when schema is put into the URL? ideally there wouldn't be much work to ensure old schemas still work

**Comment by keyserj** [comment]
Since the filter is probably going to be big, it's probably fine not to be human-readable.

Found when [searching](https://www.google.com/search?q=js+encode+and+compress+object+to+put+into+URL) for libraries that compress and URI-encode JSON:
- https://gist.github.com/gquittet/bb015a2d0ccb8e73a08e77a17e1d7aaf
- https://github.com/KilledByAPixel/JSONCrush
- https://github.com/pieroxy/lz-string
- https://github.com/Nanonid/rison (human-readable-ish)

But none of these seem to compress a magical amount. We'd probably be able to compress the JSON a lot more if we do some manual compression (e.g. shorten UUIDs to first 8 chars, assume some order of values and remove keys).

Other notes:
- would be nice if we could load a recommended filter and just use `?recommended={name}` or something and not need to see the whole filter compression until the filter changes

**Comment by Venryx** [comment]
You may already be using something like this, but this is the UUID compression library I use for debate-map: https://github.com/taskcluster/slugid

(22-char representation of uuids by using url-safe base-64-like encoding)

Of course, even 22 chars is pretty long! So further shortening that to 8 chars or something in the url also sounds reasonable.

**Comment by keyserj** [comment]
Oh that's good to know, I hadn't heard of that. Thanks for sharing

**Comment by CatGuardian** [comment]
Fantastic Wednesday Evening @keyserj!!

Hey if our main concern around the filters is not losing them when I refresh the page, then I might suggest an alternate approach to consider instead of trying to embed the filters into the URL. Instead of putting them in the URL you could save them to localStorage and just check for any filters being saved in localStorage on page load and set the filters accordingly on page load. And then when the filter settings change then save the updated blob into localStorage. Thus when you refresh the page, the filters will load from localStorage and be set to what they were.

Just an idea to float around in your head.

:)

**Comment by keyserj** [comment]
@CatGuardian That's a good point, I hadn't considered that. I think being able to share a URL and use browser back button to jump to a previous filter setting make it worth putting filter state in the URL, but potentially local storage could be a much simpler short-term solution to address the annoying page refresh issue.

**Comment by keyserj** [comment]
Lots of design thought went into this, but going to close as won't do. Mostly went back and forth between putting filter into URL vs adding custom back/forward navigation (w/local storage persistence), and decided to go with custom back/forward navigation. See https://ameliorate.app/keyserj/filters-in-url for reasoning.

Summary of reasoning:
- filter in URL has a ton of complexity for keeping URL short (not putting some params in URL if equal to defaults) and readable (keeping object params unencoded, stripping quotes/converting brackets to parens); see #394
- custom back/forward navigation is super easy implementation; see #395 
- shareable URLs will be accomplished regardless via #379
