### ISSUE TITLE
Tiles are overlapping and can't be moved

### ISSUE THREAD

**Issue by prototyperspective** [amelioro/ameliorate#535]
### Describe the bug

Below is a screenshot of how the problem map looks like for me on Firefox. The tiles are overlapping and I can't move them so they don't overlap (or to organize them). One also can't increase the tile size so the full text can be seen.

![1222](https://github.com/user-attachments/assets/c8729671-43ba-46ec-9827-0f3903bd1ce4)

### To Reproduce

1. Go to https://ameliorate.app/Prototyperspective/CarsAreHarmfulToSociety
2. If the debate is not deleted but still there (please save it) the tiles are overlapping

### Expected behavior

Being able to drag them around with the mouse (click, hold and drag). Being able to change the tile size by dragging a side of the tile. Or it arranging etc things automatically.

### Additional context

I think the full map view is not a good view mode for problem maps but is useful to have to get the full picture. Other view modes that e.g. only show a few layers at a time or the current branch would be good to add. This issue is about the full-map-view. If it's not a bug but a missing feature the issue could be moved but it seems like they are intended to be movable or can be moved but not there.

**Comment by keyserj** [comment]
Looks like I've got a few things that are scaling with the browser's default font size, but the layout calculation does not. The layout currently works on default font size of 16. Can fix this

**Comment by keyserj** [comment]
Separately - there is #196 for manually moving nodes around, but functioning automatic layout is priority over that.

And I just posted over on reddit about changing node size but I'll post it here for context as well:
> My intention was to keep node text small and concise so they can be quickly glanced at to understand high-level concepts. To this end, nodes are fixed size, and extra explanatory text can be included in the node's notes. This is open to discussion. It probably requires some practice for wording/sentence-fragmenting, but I've always been able to word nodes such that their concept fits in the current node's size.

**Comment by prototyperspective** [comment]
That makes sense. Seems like I have another font size configured in Firefox then. I also think automatic layout is a priority and ideally only that needs to be used. However, I think some changes to it would probably be good so things are less condensed and better to see – here's one main thing: I think those addresses nodes would be good to only show when hovering over a line (or when having some setting enabled)...it's too much text and too much elements.

**Comment by keyserj** [comment]
> I think those addresses nodes would be good to only show when hovering over a line (or when having some setting enabled)

I think this is a good idea, and it's actually in #478 too

**Comment by keyserj** [comment]
@prototyperspective I merged a fix, let me know if the issue still persists.

**Comment by prototyperspective** [comment]
@keyserj Great, no it's solved now as moving the tiles around is what the other issue is about, thanks. However
1. the other issue currently has the title "Ability to turn off automatic layout" and I think something about enabling moving tiles would be good to add such as "Ability to turn off automatic layout and move nodes"
2. The tiles of the connections still overlap – but it would be better to have a separate issue for that. Maybe the best solution for that is to not display info on them until hovering over the line. Is there already an issue about these tiles overlapping with (or being underneath) other tiles? The screenshots show what I mean. I think if these are shown the nodes would need to move so these can be fully seen and aren't underneath or above any other element.

![overlaps2](https://github.com/user-attachments/assets/6f67c27e-9fd4-4aae-ac53-032f70c77388) | ![overlaps1](https://github.com/user-attachments/assets/f0d90d8f-c63c-4265-ab59-739e2dc002aa)

**Comment by keyserj** [comment]
> "Ability to turn off automatic layout and move nodes"

Yeah that's a little more explicit - renamed

> The tiles of the connections still overlap

Thanks for the screenshots. A while ago I made the decision for the layout to ignore edge overlap. I think that, when a diagram gets bigger, trying to avoid the overlap results in the diagram being a lot more spread out. This is something that I'm open to reconsidering, but there's usually only one type of edge that could be between any two node types, so I don't think seeing the edge info is that big of a deal (you can also click on the edge to get it to come to the front, if you really need to see it).

Because of this, I'm also a fan of the "don't display edge details without hovering" idea.
