### ISSUE TITLE
Use specific options for layout thoroughness instead of any number

### ISSUE THREAD

**Issue by keyserj** [amelioro/ameliorate#585]
### Describe your issue

Most of the time, layout thoroughness (which allows the layout algorithm to try more layout variations to try and use space efficiently) only affects the layout for a few ranges of numbers. Usually 1 behaves differently from 2, and then sometimes 20+ can behave differently from those. For this reason, having granularity to enter any number 1-100 is not really necessary, can be cumbersome, and can give the illusion that many of the numbers should have a more significant impact.

https://github.com/user-attachments/assets/212efb6f-cdff-47c4-a0ec-bc157ac4dcc3

### Solution you'd like

Use a dropdown for layout thoroughness, where "low" = 1, "medium" = 10, and "high" = 100.

### Technical ideas and questions

Code should be pretty similar to the [Watch dropdown's code](https://github.com/amelioro/ameliorate/blob/6861b5e07af4c08c2ed44fecd0377eb448eb5c9e/src/web/topic/components/TopicPane/TopicDetails.tsx#L108-L123), except using the [current thoroughness value/onChange](https://github.com/amelioro/ameliorate/blob/6861b5e07af4c08c2ed44fecd0377eb448eb5c9e/src/web/topic/components/TopicWorkspace/MoreActionsDrawer.tsx#L415-L418) instead of making API requests:
![image](https://github.com/user-attachments/assets/dfc2508c-3ce0-43cb-9286-ae9d18d34930)

**Comment by shibv** [comment]
Hi @keyserj , I’d like to take up this task. Could you please assign it to me? 
Thanks!

**Comment by keyserj** [comment]
@shibv yep! Let me know if you run into any issues or have any questions.
