### ISSUE TITLE
Styled Popper does not disappear on the corners. 

### ISSUE THREAD

**Issue by Nezzely** [amelioro/ameliorate#81]
**Describe the bug**
Expected ScorePie component  to disappear when a score is selected or when a user moves their mouse outside of the circular dial.
When a use moves their mouse in a X pattern centered on the ScorePie the dial doesnt close when the user exits for the "corners".

**To Reproduce**
1. Go to a node
2. Click on Scoring number
3. Move mouse to 1 of the 4 corners of the bounding viewing box
4. Expected the ScorePie to disappear.

**Expected behavior**
- When a mouse is leaving the circle of the ScorePie, I expect it to disappear when mouse leaves the edge from every angle.

**Screenshots**
Expected: 
- bounding box for the mouse leave event.
- ![image](https://user-images.githubusercontent.com/34109200/224488856-7a281bd1-ab5e-458b-8478-45ef8a5be325.png)

Actual:
- bounding box for the mouse leave event
- ![image](https://user-images.githubusercontent.com/34109200/224488941-294ac924-5b3d-453f-8405-23bc90ddaf43.png)

**Additional context**
- The component uses [react-minimal-pie-chart](https://www.npmjs.com/package/react-minimal-pie-chart)
- The ScorePie has a viewing-box that is larger then the pie menu. 
- The mouse leave events fire for the whole bounding box of the component for the react-minimal-pie-chart.
   - Assumption is that the inner pie shards extend to the viewing box for the mouse leave event handler.
- The mouse leave event is actually a square.

**Technical ideas**
- Change the <Box> component to a CIRCLE that matches the inside radius circle of the react-minimal-pie-chart,
- Center the react-minimal-pie-chart within the <CircleBox> and move mouse leave events to it.

**Comment by keyserj** [comment]
@Nezzely good idea. I think a border-radius of 50% will need to be set on one (or maybe multiple) of the divs. We'll want to make sure that click-away and mouse leave both remain consistent

as for this `disappear when a score is selected`, I believe I tried putting the clickawaylistener around only the center button, but then the clickaway would register before the click of a pie segment, and decided it wasn't worth figuring out a good way to handle that

**Comment by Nezzely** [comment]
i made some headway: the child svgs are having a party with the pointer events:
https://stackoverflow.com/questions/38794884/transparent-area-of-div-using-border-radius-does-not-trigger-mouseleave
